apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: hello-world-sensor
  namespace: argo-events
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: hello-dep
      eventSourceName: webhook-hello
      eventName: hello
  triggers:
    - template:
        name: hello-world-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: batch/v1
              kind: Job
              metadata:
                generateName: hello-world-
                namespace: argo-events
              spec:
                template:
                  spec:
                    containers:
                    - name: hello
                      image: busybox
                      command: ["echo"]
                      args: ["Hello World from Argo Events!"]
                    restartPolicy: Never
                backoffLimit: 4
