apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - hello-world.yaml
  # Add new sensors here:
  # - deploy-app.yaml
  # - backup-trigger.yaml
  # - notification-sender.yaml
