---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ducklake-config
  namespace: ducklake
data:
  DUCKLAKE_CATALOG_URL: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres.ducklake.svc.cluster.local:5432/$(POSTGRES_DB)"
  DUCKLAKE_DATA_PATH: "s3://ducklake/data"