apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ducklake-cm.yaml
  - init-ducklake-job.yaml
  - minio.yaml
  - postgres-pvc.yaml
  - postgres-svc.yaml
  - statefulset.yaml
  - ingress.yaml
