---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: ducklake
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: ducklake
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:latest
        command:
        - /bin/bash
        - -c
        - minio server /data --console-address ":9001"
        envFrom:
        - secretRef:
            name: minio-secret
        ports:
        - containerPort: 9000 # S3 API port
          name: api
        - containerPort: 9001 # Web UI port
          name: console
        volumeMounts:
        - name: storage
          mountPath: /data
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: minio-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: minio-svc
  namespace: ducklake
spec:
  selector:
    app: minio
  ports:
  - name: api
    port: 9000
    targetPort: 9000
  - name: console
    port: 9001
    targetPort: 9001