apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingress 
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/reecetec/homelab-gitops.git 
    targetRevision: HEAD
    path: istio-manifests
    directory:
      recurse: true 
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
