apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo-events

resources:
  # Platform installation
  - platform
  
  # RBAC for workflows
  - rbac
  
  # Event sources (webhooks, calendars, etc.)
  - eventsources
  
  # Sensors (event processors/triggers)
  - sensors
  
  # Custom services (optional)
  - services