apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: juicebox-tls
  namespace: istio-system
spec:
  secretName: juicebox-tls-secret
  dnsNames:
  - "*.juicebox.com"
  - "juicebox.com"
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
