apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: argocd
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`homelab.local`) && PathPrefix(`/argocd`)
      priority: 10
      services:
        - name: argocd-server
          port: 80
      middlewares:
        - name: argocd-stripprefix
    - kind: Rule
      match: Host(`homelab.local`) && PathPrefix(`/argocd`) && Headers(`Content-Type`, `application/grpc`)
      priority: 11
      services:
        - name: argocd-server
          port: 80
          scheme: h2c
      middlewares:
        - name: argocd-stripprefix