# https://argo-cd.readthedocs.io/en/stable/operator-manual/cluster-bootstrapping/
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
  # This finalizer ensures that if you delete the root app, Argo CD will also delete all the child apps it created.
  finalizers:
    - argoproj.io/resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/reecetec/homelab-gitops.git
    targetRevision: HEAD
    path: apps
    directory:
      recurse: true 
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true