createUserJob:
  useHelmHooks: false
  applyCustomEnv: false
migrateDatabaseJob:
  useHelmHooks: false
  applyCustomEnv: false


dags:
  gitSync:
    enabled: true
    repo: https://github.com/juicebox-platform/sportsflow.git
    rev: HEAD
    branch: main
    subPath: dags

redis:
  # passwordSecretName: airflow-redis-password
  auth:
    enabled: false