apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: addons
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/reecetec/homelab-gitops.git
    targetRevision: HEAD
    path: addons
  destination:
    server: https://kubernetes.default.svc
    # The namespace doesn't matter as much here since the manifest has one specified
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
