apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
spec:
  project: default
  source:
    chart: airflow
    repoURL: https://airflow.apache.org
    targetRevision: 1.18.0
    helm:
      values: |
        createUserJob:
          useHelmHooks: false
        migrateDatabaseJob:
          useHelmHooks: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: airflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
